### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by zackradisic** [zackradisic/aussieplusplus#5]
### General
- [ ] Try/catch (`WHATYARECKON<> AAHSHELLBERIGHT <>`) and throwing errors (`STREWTH <value>`) #1 
- [ ] Modules and imports/exports #3
- [ ] Data types/structures. We need objects and arrays #13 
- [ ] Some form of bundling data / encapsulation (classes or structs, though I prefer the Go/Rust struct way) #13 
- [ ] Expand standard lib. filesystem IO, network IO (would love to make an aussie web-server), utilities. #12 
- [ ] Make `YA RECKON`s expressions, see #15 

### Things to discuss / huge undertakings
- [ ] Type system
- [ ] Concurrency, think the easiest way to implement this is an event loop #2 

If you have any ideas for any of the features above, feel free to make an issue so we can discuss about it there

**Comment by bbrk24** [comment]
Silly suggestion: Since we're already using `<>` for braces, if/when a type system is implemented, use `{}` for generics

**Comment by jwfxpr** [comment]
Love that suggestion @bbrk24.  In strayan and pommy (and possibly in yankee?) a "curly one" is a question that's tricky or not straightforward. So a method using `{}` for generics would for sure be a `CURLY ONE` 😆

**Comment by jwfxpr** [comment]
@zackradisic as discussed in #15, convert `YA RECKON` to expression
